### PR TITLE
Added parameters to diff URI

### PR DESCRIPTION
**Pull request by patel-nikhil**

### CODE REVIEW

**Comment by ReviewerOfCode** [comment]
I generated a SimpleDiff here -> https://tranquil-earth-41184.herokuapp.com/diff?targetBranch=master&repoSlug=itsAlexNguyen/samples&pullRequestID=5

**Review by itsAlexNguyen — APPROVED** [review]

**Comment by ReviewerOfCode** [comment]
I generated a SimpleDiff here -> http:/localhost:8080/diff?targetBranch=master&repoSlug=itsAlexNguyen/samples&pullRequestID=5

**Comment by ReviewerOfCode** [comment]
I generated a SimpleDiff here -> http:/localhost:8080/diff?targetBranch=master&repoSlug=itsAlexNguyen/samples&pullRequestID=5

**Comment by ReviewerOfCode** [comment]
I generated a SimpleDiff here -> http:/localhost:8080/diff?targetBranch=master&repoSlug=itsAlexNguyen/samples&pullRequestID=5

**Comment by ReviewerOfCode** [comment]
I generated a SimpleDiff here -> http:/localhost:8080/diff?targetBranch=master&repoSlug=itsAlexNguyen/samples&pullRequestID=5

**Comment by ReviewerOfCode** [comment]
I generated a SimpleDiff here -> https:/simplediff-feature-add-mfxejzg.herokuapp.com/diff?targetBranch=master&repoSlug=itsAlexNguyen/samples&pullRequestID=5

**Comment by ReviewerOfCode** [comment]
I generated a SimpleDiff here -> https://simplediff-feature-add-mfxejzg.herokuapp.com/diff?targetBranch=master&repoSlug=itsAlexNguyen/samples&pullRequestID=5

**Comment by ReviewerOfCode** [comment]
I generated a SimpleDiff here -> https://simplediff-feature-add-mfxejzg.herokuapp.com/diff?targetBranch=master&repoSlug=itsAlexNguyen/samples&pullRequestID=5

**Comment by ReviewerOfCode** [comment]
I generated a SimpleDiff here -> https://simplediff-feature-add-mfxejzg.herokuapp.com/diff?targetBranch=master&repoSlug=itsAlexNguyen/samples&pullRequestID=5

**Comment by ReviewerOfCode** [comment]
I generated a SimpleDiff here -> http://localhost:8080/diff?targetBranch=master&repoSlug=itsAlexNguyen/samples&pullRequestID=5

**Pull request merged**
